---
title: "TDI Daily Max"
author: "Molly Williams"
date: "3/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Load packages and data

```{r}

library(here)
library(tidyverse)
library(lubridate)
library(janitor)


# import data and add columns for water year, month and day (Oct 1 = 1, Nov 1 = 32 etc through 365-66 for each year)
#rcp45 <- read_csv("tdi/RCP45_dailymax.csv") %>% 
#  mutate(water_year = ifelse(Month>9, Year+1, Year)) %>% 
#  mutate(water_month = ifelse(Month<10, Month+3, ifelse(Month>9, Month-9, Month))) %>% 
#  mutate(date_combine = make_datetime(water_year, water_month, Day)) %>% 
#  mutate(water_day = yday(date_combine)) %>%  # extract day of year from combined date

### some discrepancies here because of mismatched days/months (e.g. for 1981 water day 60 is duplicated); check dupes:
# rcp_test <- rcp45 %>% filter(water_year == 1985)

# dupes5 <- get_dupes(rcp_test, water_day) %>% 
#  select(Year, Month, Day, water_year, water_month, water_day, dupe_count)


### Doesn't seem like there's a good way to address this issue without over-manipulating the dates, so going to try a different method. It's not the most elegant, but it works:

leap_years <- c(1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080, 2084, 2088, 2092, 2096)

# Create water day column for data from leap years
rcp45_1 <- read_csv("tdi/RCP45_dailymax.csv") %>% 
  mutate(water_year = ifelse(Month>9, Year+1, Year)) %>% 
  mutate(water_month = ifelse(Month<10, Month+3, ifelse(Month>9, Month-9, Month))) %>% 
  filter(water_year %in% leap_years) %>%
  filter(water_year != 1980) %>% # keeping only complete data years
  mutate(water_day = rep(1:366, 29)) 

# Create water day column for data from non-leap years
rcp45_2 <- read_csv("tdi/RCP45_dailymax.csv") %>% 
  mutate(water_year = ifelse(Month>9, Year+1, Year)) %>% 
  mutate(water_month = ifelse(Month<10, Month+3, ifelse(Month>9, Month-9, Month))) %>% 
  filter(!water_year %in% leap_years) %>% 
  filter(water_year != 1980) %>% # keeping only complete data years
  mutate(water_day = rep(1:365, 90))

# Combine into a single data frame
rcp45 <- rbind(rcp45_1, rcp45_2)



## Repeat for RCP 8.5 data: 
# Create water day column for data from leap years
rcp85_1 <- read_csv("tdi/RCP85_dailymax.csv") %>% 
  mutate(water_year = ifelse(Month>9, Year+1, Year)) %>% 
  mutate(water_month = ifelse(Month<10, Month+3, ifelse(Month>9, Month-9, Month))) %>% 
  filter(water_year %in% leap_years) %>%
  filter(water_year != 1980) %>% # keeping only complete data years
  mutate(water_day = rep(1:366, 29)) 

# Create water day column for data from non-leap years
rcp85_2 <- read_csv("tdi/RCP85_dailymax.csv") %>% 
  mutate(water_year = ifelse(Month>9, Year+1, Year)) %>% 
  mutate(water_month = ifelse(Month<10, Month+3, ifelse(Month>9, Month-9, Month))) %>% 
  filter(!water_year %in% leap_years) %>% 
  filter(water_year != 1980) %>% # keeping only complete data years
  mutate(water_day = rep(1:365, 90)) 

# Combine into a single data frame
rcp85 <- rbind(rcp85_1, rcp85_2)

```



# Isolate 10 largest flow days from each year and model

```{r}

# Convert to long/tidy data
rcp45_long <- rcp45 %>% 
  select(-Year, -Month, -Day) %>% 
  pivot_longer(-c(water_year, water_month, water_day), names_to = "model", values_to = "flow") %>% 
  mutate(rcp = 4.5)

rcp85_long <- rcp85 %>% 
  select(-Year, -Month, -Day) %>% 
  pivot_longer(-c(water_year, water_month, water_day), names_to = "model", values_to = "flow") %>% 
  mutate(rcp = 8.5)


# Combine all data into single df

all_daily_flows <- rbind(rcp45_long, rcp85_long)


# Find top 10 flow values for each model and each year
top10_annual_flows <- all_daily_flows %>% 
  group_by(water_year, model, rcp) %>% 
  top_n(10, flow) %>% 
  write_csv("tdi/top10_annual_flows.csv")

# all the top 10 flows are within a consecutive streak 


# If top 10 flows fall within consecutive streak(s) of water_days, take only the highest value from each streak

group_by(rcp, model, water_year) %>% 
function() that asks:
#  do water_day values fall within consecutive streak(s)?
#  if yes, retain only max value
  
# create a for loop for this? save all of the diff models in csvs , then re-import perform the operations on them

  set.seed(201)
rnums = rnorm(100)
runs = rle(rnums > 0)
  
  
```


